service: sls-node-s3-image-recognition-demo

frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  bucket: fudanzz-image-upload

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  endpointType: regional
  profile: admin
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "rekognition:*"
      Resource: "*" 

functions:
  helloWorld:
    handler: function/helloWorld.handler
    events:
      - http:
          path: hello
          method: get
  processImage:
    handler: function/processImage.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .jpg
